apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins
  containers:
  - name: gcloud
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine
    command: ["cat"]
    tty: true
  - name: kubectl
    image: alpine/k8s:1.35.9
    command: ["cat"]
    tty: true
